name: NPM CI
on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  npm-ci-job:
    name: "YARN & NPM Build Test"
    runs-on: ubuntu-latest
    timeout: 25
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'     
      - name: Restore cached NODE modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v4-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v4-dependencies-${{ hashFiles('yarn.lock') }}
            v4-dependencies- 
      - name: "YARN install"
        run: yarn install --frozen-lockfile
      - name: "NPM run build"
        run: npm run build && npm run build:types
      - name: "Code linting"
        run: npm run lint
      - name: "Tests - Mocha"
        run: npm run test:node
      - name: "Tests - BrowserStack"
        run: npm run test:bs
        env:
          BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
          BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

  # Publish job will be run only when the changes are merged to Master branch
  npm-deploy-job:
    name: "NPM Publish from Master"
    runs-on: ubuntu-latest
    needs: npm-ci-job
    if: github.ref == 'refs/heads/master' 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'  
          registry-url: https://registry.npmjs.org
      - name: Restore cached NODE modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v4-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v4-dependencies-${{ hashFiles('yarn.lock') }}
            v4-dependencies- 
      - name: "Publish packages"
        run: "npx lerna publish --message 'chore: releasing new packages versions' --yes"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          